---
title: "Secondary data Analysis- Cover Story Analysis"
author: "siju.swamy@saintgits.org"
date: "1/18/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r ,message=FALSE, warning=FALSE}
# Cleaning of data
library(tidyverse)
#df=read.csv('SR_data2.csv',head=TRUE)
df=read.csv('datafinal.csv',head=TRUE)
df=na.omit(df)
library(stringr)
library(psych)
library(kableExtra)
library(gmodels)
set.seed(42)
library(magrittr)
library(qwraps2)
# Load function
source("http://pcwww.liv.ac.uk/~william/R/crosstab.r")
```
## Exploratory Analysis of Science Reporter for last Ten years

```{r}
df$Year=as.factor(df$Year)
df$Gender<- factor(df$Gender)
levels(df$Gender) <-c("Female","Male")
```
```{r}
crosstab(df,col.vars =c("Year") ,row.vars =c("Authorship.type"),type=c("f"),style='long')
```
```{r,include=FALSE}
library(dplyr)
#df$Title=as.factor(df$Title)
df$State=as.factor(df$State)
catd <- df %>%
  filter(Year %in% c("2010", "2011","2012","2013","2014","2015","2016","2017","2018","2019","2020")) %>%
  group_by(State) %>%
  summarise(counts = n()) 
  #catd <- catd %>%
  #arrange(commu_cat, desc(dist)) %>%
  #mutate(lab_ypos = cumsum(counts) - (.55*counts))
#head(catd, 25)
```

```{r,include=FALSE}
library(dplyr)
catd <- df %>%
 filter(Gender %in% c("Female", "Male")) %>%
  group_by(Gender,State,Year) %>%
  summarise(counts = n()) 
  #catd <- catd %>%
  #arrange(commu_cat, desc(dist)) %>%
  #mutate(lab_ypos = cumsum(counts) - (.55*counts))
head(catd, 4)
```
```{r,,fig.margin=TRUE,fig.width=4.5,fig.width=4.5}
library(kableExtra)
library(reshape2)
ncatd=dcast(catd,State~Gender,value.var ="counts")
ncatd$Total=apply(ncatd[,2:3],1,sum)
kable(ncatd) %>%
  kable_styling(bootstrap_options = c("striped", "hover"),full_width = F,position = "center")
xtable::xtable(ncatd)
```
```{r,,fig.margin=TRUE,fig.width=4.5,fig.width=4.5}
library(ggplot2)
# Create stacked bar graphs with labels
ggplot(catd, aes(x = Gender, y = counts,label=counts)) +
  geom_bar(aes(color = Year, fill = Year), stat = "identity") +labs(x ="Gender", y = "Number of Cover Stories",fill="Year")
```
```{r}
#statewise auther data
library(ggplot2)
bp=ggplot(df,aes(x=Gender))+
  geom_bar(aes(fill=State))+facet_wrap(~Year)
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.8,position = position_stack(0.8), size = 3.5)+labs(x ="Gender", y = "Number of Cover Stories",fill="State")
```
```{r}
#statewise auther data
library(ggplot2)
bp=ggplot(df,aes(x=Gender))+
  geom_bar(aes(fill=Gender))+facet_wrap(~Year)
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.8,position = position_stack(0.8), size = 3.5)+labs(x ="Gender", y = "Number of Cover Stories")+theme(legend.position="none")
```

```{r}
#statewise auther data
library(ggplot2)
bp=ggplot(df,aes(x=State,group=Year))+
  geom_bar(aes(fill=Year))#+facet_wrap(~State)
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.8,position = position_stack(0.8), size = 2.5)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+labs(x ="State", y = "Number of Publications",fill="Year")
```
```{r}
#statewise author data
library(ggplot2)
bp=ggplot(df,aes(x=State,group=Gender))+
  geom_bar(aes(fill=Gender))#+facet_wrap(~State)
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.8,position = position_stack(0.8), size = 2.5)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+labs(x ="State", y = "Number of Publications")
```
```{r}
#statewise
library(ggplot2)
bp=ggplot(df,aes(x=reorder(AR_Category,AR_Category,function(x)-length(x)),group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.8,position = position_stack(0.8), size = 3.5)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+labs(x ="AR Category", y = "Number of Cover Stories",fill="Authorship type")
```
```{r}
## for ANOVA test
df$FRE_index=(df$FRE_Score-min(df$FRE_Score))/(max(df$FRE_Score)-min(df$FRE_Score))
```
```{r}
library(dplyr)
library(kableExtra)
FSa=group_by(df, Subject_Area) %>%
  summarise(
    count = n(),
    mean = mean(as.integer(AR_Index)
, na.rm = TRUE),
    sd = sd(as.integer(AR_Index)
, na.rm = TRUE)
  )
#Fsa=cbind.data.frame(FSa)
kable(FSa) %>%
  kable_styling(bootstrap_options = c("striped", "hover"),full_width = F,position = "center")
#xtable::xtable(FSa)
```
```{r}
# testing of difference of mean
t1=t.test(as.integer(df$AR_Index)~df$Gender,var.equal=TRUE)
```
```{r}
##ANOVA
xtable::xtable(aov((as.integer(df$AR_Index)~df$Subject_Area)))
```

```{r}
#statewise
library(ggplot2)
bp=ggplot(df,aes(x=Gender))+
  geom_bar(aes(fill=Gender))+facet_wrap(~State)
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.4,position = position_stack(0.4), size = 2.5)+labs(x ="Gender", y = "Number of Cover Stories")+theme(legend.position="none")
```

```{r}
#Authership type over gender with respect to State over years
```


```{r}
library(ggplot2)
bp=ggplot(df,aes(x=Gender,group=Year))+
  geom_bar(aes(fill=Year))+facet_wrap(~State)
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.7,position = position_stack(0.7), size = 2.5)+labs(x ="Gender", y = "Number of Cover Stories",fill="Year")
```
```{r}
library(vcd)
library(vcdExtra)
```

```{r}
#two-way
tw=ftable(df$Gender~df$State)
chisq.test(tw)
```

```{r}
tw=ftable(df$Gender~df$State+df$Year)
fisher.test(tw,simulate.p.value=TRUE)
```


```{r}
#Authership type over gender with respect to subject area
library(ggplot2)
bp=ggplot(df,aes(x=Gender,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))+facet_wrap(~Subject_Area)
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.8,position = position_stack(0.7), size = 3.5)+labs(x ="Gender", y = "Number of Cover Stories",fill="Authorship type")
```

```{r}
#Authership type over gender with respect to FRE Category
library(ggplot2)
bp=ggplot(df,aes(x=Gender,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))+facet_wrap(~FRE_Category)
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.8,position = position_stack(0.7), size = 3.5)+labs(x ="Gender", y = "Number of Cover Stories",fill="Authorship type")
```

```{r}
#Authership type over gender with respect to GF_Category
library(ggplot2)
bp=ggplot(df,aes(x=Gender,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))+facet_wrap(~GF_Category)
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.8,position = position_stack(0.7), size = 3.5)+labs(x ="Gender", y = "Number of Cover Stories",fill="Authorship type")
```
```{r}
#Authership type over gender with respect to FKG_Category
library(ggplot2)
bp=ggplot(df,aes(x=Gender,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))+facet_wrap(~FKG_Category)
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.8,position = position_stack(0.7), size = 3.5)+labs(x ="Gender", y = "Number of Cover Stories",fill="Authorship type")
```

```{r}
#Authership type over gender with respect to CL_Category
library(ggplot2)
bp=ggplot(df,aes(x=Gender,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))+facet_wrap(~CL_Category)
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.8,position = position_stack(0.7), size = 3.5)+labs(x ="Gender", y = "Number of Cover Stories",fill="Authorship type")
```
```{r}
#Authership type over gender with respect to SMOG grade
library(ggplot2)
bp=ggplot(df,aes(x=Gender,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))+facet_wrap(~SMOG_Grade)
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.8,position = position_stack(0.7), size = 3.5)+labs(x ="Gender", y = "Number of Cover Stories",fill="Authorship type")
```
```{r}
#Authership type over gender with respect to AR_Category
library(ggplot2)
bp=ggplot(df,aes(x=Gender,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))+facet_wrap(~AR_Category)
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.8,position = position_stack(0.7), size = 3.5)+labs(x ="Gender", y = "Number of Cover Stories",fill="Authorship type")
```
```{r}
#Authership type over gender with respect to LWF_Category
library(ggplot2)
bp=ggplot(df,aes(x=Gender,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))+facet_wrap(~LWF_Grade)
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.8,position = position_stack(0.7), size = 3.5)+labs(x ="Gender", y = "Number of Cover Stories",fill="Authorship type")
```
```{r}
#Authership type over gender with respect to RC_Category
library(ggplot2)
bp=ggplot(df,aes(x=Gender,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))+facet_wrap(~RC_Category)
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.8,position = position_stack(0.7), size = 3.5)+labs(x ="Gender", y = "Number of Cover Stories",fill="Authorship type")
```
```{r}
#Authership type over gender with respect to RC_grade
library(ggplot2)
bp=ggplot(df,aes(x=Gender,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))+facet_wrap(~RC_Grade)
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.8,position = position_stack(0.7), size = 3.5)+labs(x ="Gender", y = "Number of Cover Stories",fill="Authorship type")
```

```{r}
#Authership type over gender 
library(ggplot2)
bp=ggplot(df,aes(x=Gender,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=2,position = position_stack(0.2), size = 3.5)+labs(x ="Gender", y = "Number of Cover Stories",fill="Authorship type")
```
```{r}
#state over gender 
library(ggplot2)
bp=ggplot(df,aes(x=Gender,group=State))+
  geom_bar(aes(fill=State))
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.6,position = position_stack(0.7), size = 3.5)+labs(x ="Gender", y = "Number of Cover Stories",fill="State")
```
```{r}
#Authership type over Subject_Area
 
library(ggplot2)
bp=ggplot(df,aes(x=Subject_Area

,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.5,position = position_stack(0.5), size = 2.5)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+labs(x ="Subject_Area

", y = "Number of Cover Stories",fill="Authorship type")
```


```{r}
#Authership type over state 
library(ggplot2)
bp=ggplot(df,aes(x=State,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.5,position = position_stack(0.5), size = 2.5)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+labs(x ="State", y = "Number of Cover Stories",fill="Authorship type")
```

```{r}
#Authership type over years 
library(ggplot2)
bp=ggplot(df,aes(x=Year,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.5,position = position_stack(0.5), size = 2.5)+labs(x ="Year", y = "Number of Cover Stories",fill="Authorship type")
```

```{r}
#Authership type over FRE_category 
library(ggplot2)
bp=ggplot(df,aes(x=FRE_Category
,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.5,position = position_stack(0.5), size = 2.5)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+labs(x ="FRE Category
", y = "Number of Cover Stories",fill="Authorship type")
```

```{r}
#Authership type over GF_Category 
library(ggplot2)
bp=ggplot(df,aes(x=GF_Category
,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.5,position = position_stack(0.5), size = 2.5)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+labs(x ="GF_Category
", y = "Number of Cover Stories",fill="Authorship type")
```

```{r}
#Authership type over FKG_Category 
library(ggplot2)
bp=ggplot(df,aes(x=FKG_Category
,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.5,position = position_stack(0.5), size = 2.5)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+labs(x ="FKG_Category
", y = "Number of Cover Stories",fill="Authorship type")
```

```{r}
#Authership type over CL_Category 
library(ggplot2)
bp=ggplot(df,aes(x=CL_Category
,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.5,position = position_stack(0.5), size = 2.5)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+labs(x ="CL_Category
", y = "Number of Cover Stories",fill="Authorship type")
```

```{r}
#Authership type over SMOG_Grade
 
library(ggplot2)
bp=ggplot(df,aes(x=SMOG_Grade,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.5,position = position_stack(0.5), size = 2.5)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+labs(x ="SMOG_Grade", y = "Number of Cover Stories",fill="Authorship type")
```
```{r}
#Authership type over AR_Category
 
library(ggplot2)
bp=ggplot(df,aes(x=AR_Category,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.5,position = position_stack(0.5), size = 2.5)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+labs(x ="AR_Category", y = "Number of Cover Stories",fill="Authorship type")
```

```{r}
#Authership type over AR_Age
 
library(ggplot2)
bp=ggplot(df,aes(x=AR_Age,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.5,position = position_stack(0.5), size = 2.5)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+labs(x ="AR_Age", y = "Number of Cover Stories",fill="Authorship type")
```

```{r}
#Authership type over LWF_Grade
 
library(ggplot2)
bp=ggplot(df,aes(x=LWF_Grade,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.5,position = position_stack(0.5), size = 2.5)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+labs(x ="LWF_Grade", y = "Number of Cover Stories",fill="Authorship type")
```

```{r}
#Authership type over RC_Category
 
library(ggplot2)
bp=ggplot(df,aes(x=RC_Category,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.5,position = position_stack(0.5), size = 2.5)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+labs(x ="RC_Category", y = "Number of Cover Stories",fill="Authorship type")
```

```{r}
#Authership type over RC_Age
 
library(ggplot2)
bp=ggplot(df,aes(x=RC_Age,group=Authorship_type))+
  geom_bar(aes(fill=Authorship_type))
bp+geom_text(stat='count', aes(label = after_stat(count)), vjust=0.5,position = position_stack(0.5), size = 2.5)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+labs(x ="RC_Age", y = "Number of Cover Stories",fill="Authorship type")
```


```{r}
#Authership type over gender with respect to State
library(ggplot2)
bp=ggplot(df,aes(x=Gender))+
  geom_bar(aes(fill=Authorship_type))+facet_wrap(~State)
bp+labs(x ="Gender", y = "Number of Cover Stories",fill="Authorship type")
```

```{r}
library(ggplot2)
bp=ggplot(df,aes(x=Year))+
  geom_bar(aes(fill=Gender))+facet_wrap(~State)
bp+labs(x ="", y = "Number of Cover Stories",fill="Gender")
```



## State-wise distribution of Publications for the last 10 years
```{r}
library(plotly)
df1=filter(df,Gender=="Female")
Temp=table(df$Subject_Area)
fig <- plot_ly(type='pie', labels=names(Temp), values=Temp,  textinfo='label+percent',
              
               insidetextorientation='radial',showlegend=F)
fig
```

## Test whether this difference is significant

```{r}
chisq.test(table(df1$State))
```


```{r}
fig1 <- plot_ly(df, x = ~dated, y = ~npub)
fig1 <- fig1 %>% add_lines(name = ~"Number of Publications")
fig2 <- plot_ly(df, x = ~dated, y = ~Gender)
fig2 <- fig2 %>% add_lines(name = ~"Gender")
fig <- subplot(fig1, fig2)

fig
```

## Text analysis

```{r}
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
```

## Loading Data

```{r}
text=read.csv("SR_data1.csv")
docs <- Corpus(VectorSource(text$Author_name))
```

```{r}
inspect(docs)
```

## Text Cleaning

```{r}
toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
#docs <- tm_map(docs, toSpace, ",")
docs <- tm_map(docs, toSpace, "\\|")
```
```{r}
# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("english"))
# Remove your own stop word
# specify your stopwords as a character vector
docs <- tm_map(docs, removeWords, c("blabla1", "blabla2")) 
# Remove punctuations
#docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)
# Text stemming
# docs <- tm_map(docs, stemDocument)
```

## Build Document-term matrix

```{r}
dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v,row.names = NULL)
head(d, 10)
```

## Creating a Word cloud

```{r}
#par(bg="grey10")
set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 10,
          max.words=1500, random.order=FALSE, rot.per=0.1,col=brewer.pal(8, "Dark2"))
#colors=terrain.colors(length(d$word), alpha=0.94)
```

## Plot word frequencies

```{r}
barplot(d[1:50,]$freq, las = 2, names.arg = d[1:50,]$word,
        col ="lightblue",
        ylab = "Word frequencies")
```

## Term frequencies

```{r}
findFreqTerms(dtm, lowfreq = 40)

```

## Associated words

```{r}
findAssocs(dtm, terms = "kumar", corlimit = 0.2)

```

